### ISSUE TITLE
Can't install on Linux Mint 20

### ISSUE THREAD

**Issue by thomaspaulb** [bamidev/stonenet#1]
```
The following packages have unmet dependencies:
 stonenet : Depends: libc6 (>= 2.34) but 2.31-0ubuntu9.14 is to be installed
```

**Comment by thomaspaulb** [comment]
So I upgraded to Mint 21 which is based on Ubuntu jammy and now it works. My system upgrade was due anyway, but it would of course be nice if it works on older Ubuntu versions.

**Comment by bamidev** [comment]
Hmmm, yeah I had a similar error at some point, because it turned out I hadn't upgraded to the new debian version yet.

But I've configured a certain version of the rust compiler to be used in stonenet, and that requires a certain version of libc.

I've googled around and apparently I can have the rust compiler link it against musl instead of glibc, which would be done statically. But the problem is that stonet also depends on SQLite 3. And the `libsqlite3-0` package on debian is build on glibc, not musl, so then I would also have to bundle sqlite or link to it statically as well. 
It can be done, but I don't think it is really worth it to bundle sqlite into stonenet by default for linux.

However, I would be able to add a `stonenet-bundled` package to the repo maybe...

**Comment by bamidev** [comment]
Ok, I have no problem compiling the bundled packages, but I have to take some time to see how I can have these bundled packages co-exist in the same package repo.

**Comment by thomaspaulb** [comment]
Well if you're going for bundling, you might as well use something like [Tauri](https://tauri.app/v1/guides/building/) and have full-fledged cross-platform working bundles. I'm not sure that's the phase of the project now, on the other hand, it would make it a lot easier for a whole bunch of people to install it.

**Comment by bamidev** [comment]
Yeah Tauri has a one problem:

I intend to have a windows installer at some point, but Tauri uses the Wix toolset for that, which can only generate the installer/setup file from a windows machine. And I don't want to bother with windows every time I release a new version. :p Right now I am already building a .exe file from my debian installation everytime.

But I have already successfully set up the bundled builds. I still need to test them on a system with an older libc version or something.  And I also need to figure out how I can configure my package repo to have both 'type' of packages in it.

**Comment by ddejong-therp** [comment]
Alright, packages that have libsqlite3 and musl (an alternative for libc) statically linked are now available when using this apt line:
```
deb http://get.stonenet.org/debian stable bundled
```
Which should work for older systems. Next up: nix packages.

**Comment by bamidev** [comment]
Alright, packages that have libsqlite3 and musl (an alternative for libc) statically linked are now available when using this apt line:
```
deb http://get.stonenet.org/debian stable bundled
```
Which should work for older systems. Next up: nix packages.
